
variables:
  GIT_SUBMODULE_STRATEGY: recursive

.test:
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug
    - cmake --build . --config Debug
    - ctest --build-config Debug --output-on-failure

windows:
  extends: .test
  tags:
    - windows

linux:
  before_script:
    - apt-get update -y
    - apt-get install -y libpcap-dev
  extends: .test
  tags:
    - docker
  image: rikorose/gcc-cmake
